### ISSUE TITLE
Feature request: Typeorm snippets

### ISSUE THREAD

**Issue by ahmedNY** [ashinzekene/vscode-nestjs-snippets#10]
Typeorm is an awesome ORM for typescript, it's had a builtin support in nest-js
it will be nice if we had snippets for **entity**, and **repository** files

**Comment by ashinzekene** [comment]
Cool. You can make a PR if you like

**Comment by ahmedNY** [comment]
https://github.com/ashinzekene/vscode-nestjs-snippets/pull/11
