### ISSUE TITLE
Consider restructuring names

### ISSUE THREAD

**Issue by wbhob** [ashinzekene/vscode-nestjs-snippets#2]
Many of the names and prefixes are weirdly hyphenated. Consider just renaming to "Nest Snippets".

| Name | Prefix |
| --- | --- |
|`nest-controller` | `n-c`|
|`nest-service` | `n-s` |

Keeping it short like this makes it easier for your users. Cheers!

**Comment by ashinzekene** [comment]
Thanks for the suggestion. You can make a pr
