### ISSUE TITLE
Dosen't support Pipe?

### ISSUE THREAD

**Issue by suiyi8760** [ashinzekene/vscode-nestjs-snippets#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution).macOS(Yosemite ? El Capitan? Sierra ?)
macOS 10.13.6
### Versions
  > latest

### Repro steps
  >

### The log given by the failure.
>

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ashinzekene** [comment]
Can you create a PR for it?

**Comment by suiyi8760** [comment]
@ashinzekene Sure.I'll have a look after work.

**Comment by ashinzekene** [comment]
Cool
