### ISSUE TITLE
Update to v5

### ISSUE THREAD

**Issue by dreamdevil00** [ashinzekene/vscode-nestjs-snippets#5]
Have you considered update the snippets to use nestjs v5?

**Comment by dreamdevil00** [comment]
> Its already on v5. Did you spot any snippet that's not?

I am using nestjs v5.3.11, and type `n-interceptor` But it seems it is still using depracated `@interceptor()` and the `intercept()` method args mismatch current version. Please take a look

**Comment by dreamdevil00** [comment]
Rxjs import path should also  change to v6.

**Comment by ashinzekene** [comment]
Okay, I'd look into it.

You can also make PR's if you want to

**Comment by dreamdevil00** [comment]
I’d glad to do it
